Repository PM-Dungeon/dungeon-starter, pull requests merged in 2022-05, with the labels that each got.

#99 [BUG] Position des Ausganges in Level1 ungünstig
  code/assets/level/files/level1.json
Labels: bug

#103 Update github_ci.yml checkstyle
  .github/workflows/github_ci.yml
Labels: bug

#107 Update workflow github_ci.yml
  .github/workflows/github_ci.yml
Labels: enhancement

#109 Update buildscript to that one in core/version4
  code/build.gradle
Labels: enhancement

#111 Quickstart: getTexture -> getTexturePath
  documentation/quickstart_de.md
Labels: bug, enhancement

#116 Update gson version
  code/build.gradle
Labels: enhancement, toolchain
